version: "3.3"
services:
  backend-worker:
    build: ./b
    command: >
      bash -c "uvicorn api.main:app --host 0.0.0.0 --reload & 
                python /app/api/worker.py"
    volumes:
      - ./b:/app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/proyecto-desarrollo-cloud.json
      - GOOGLE_CLOUD_PROJECT=proyecto-desarrollo-cloud
      - PUBSUB_TOPIC=projects/proyecto-desarrollo-cloud/topics/ejemplo123
      - PUBSUB_SUBSCRIPTION=projects/proyecto-desarrollo-cloud/subscriptions/ejemplo123-sub


  # worker:
  #   build: ./b
  #   command: python /app/api/worker.py
  #   volumes:
  #     - ./b:/app
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/app/proyecto-desarrollo-cloud.json
  #     - GOOGLE_CLOUD_PROJECT=e2-esc
  #     - PUBSUB_TOPIC=projects/e2-dsc/subscriptions/pubsub-sub
  #     - PUBSUB_SUBSCRIPTION=projects/e2-dsc/subscriptions/pubsub-sub

